### ISSUE TITLE
issue about "/app/__init__.py"

### ISSUE THREAD

**Issue by DoubleAix** [hawzie197/Flask_Angular4_Skeleton#2]
i think "from config import config" should be rewritten to "from ..config import config" or config.py should be moved to /app/

**Comment by hawzie197** [comment]
Sure thing. If you want to update it and create a pull request, that would be great!

**Comment by DoubleAix** [comment]
OKOK, I didn't do it before. let me take a chance to try it !!

**Comment by emishaikh** [comment]
i am not able to run application , I have dist folder in static file, when i am running server and navigating to http://localhost:3000 i am getting this error



GET http://localhost:3000/inline.bundle.js net::ERR_ABORTED
GET http://localhost:3000/styles.bundle.js net::ERR_ABORTED
GET http://localhost:3000/polyfills.bundle.js net::ERR_ABORTED
GET http://localhost:3000/scripts.bundle.js net::ERR_ABORTED
GET http://localhost:3000/vendor.bundle.js net::ERR_ABORTED
GET http://localhost:3000/main.bundle.js net::ERR_ABORTED

But these files are there in dist, i don know, what is happening

**Comment by hawzie197** [comment]
Hi emishaikh, when you run the application, depending on if you are running the flask server, there will be different url routes.

If you are simply running the angular server by:
`ng serve`, you will need to navigate to http://localhost:4200

If you are running both the flask server and the angular server using:
`python3 manage.py runserver` to run flask server and
`ng build --dev --watch` to run and build the angular server,
you will need to navigate to http://localhost:5000

Try this out and if you are still unable to launch the webapp I will dive deeper.
