### ISSUE TITLE
how can I access the models form services

### ISSUE THREAD

**Issue by romarro** [hawzie197/Flask_Angular4_Skeleton#4]
Hi, sorry for the basic question, I am kinda new to all this. 
I am a model in the models folder and I want to access that model in a service defined in the service folder.
python as I read has a problem with accessing siblings folders content. Relative path doesn't work ( I didn't found a way to make it work)

**Comment by hawzie197** [comment]
Hi @romarro,

Here is a little bit of code to access the models from the services directory:

Put the code below inside your file inside the services directory:
`from ..models.models import *`

or to import individual classes:
`from ..models.models import YOURCLASSNAME`

Let me know how this helps.

- Michael

**Comment by romarro** [comment]
thanks
